{% set name = "gifsicle" %}
{% set version = "1.93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kohler/gifsicle/archive/v{{ version }}.tar.gz
  sha256: 941c0b1c3ebc748949a0d14363f0fb3c9d2c06ee122b3548315b9233eb956d88

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - autoconf
    - automake
    - {{ compiler('c') }}

test:
  commands:
    - gifsicle --help

about:
  home: http://www.lcdf.org/gifsicle/
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: Create, manipulate, and optimize GIF images and animations

  description: |
    Gifsicle manipulates GIF image files. Depending on command line 
    options, it can merge several GIFs into a GIF animation; explode 
    an animation into its component frames; change individual frames 
    in an animation; turn interlacing on and off; add transparency; add 
    delays, disposals, and looping to animations; add and remove comments; 
    flip and rotate; optimize animations for space; change images' 
    colormaps; and other things.
  doc_url: http://www.lcdf.org/gifsicle/
  dev_url: https://github.com/kohler/gifsicle

extra:
  recipe-maintainers:
    - jan-janssen
